### ISSUE TITLE
Build and Publish Arm Docker images for Go

### ISSUE THREAD

**Issue by bradrydzewski** [drone/tutorials#1]
this tutorial should focus on building arm64 Docker images for Golang and publishing to the registry. It should discuss how to cross-compile the code on amd64 systems (e.g. mac) and how to run arm64 images locally using Docker for mac / windows. It should also include instructions to setup Drone to continuously build and publish these docker images.

**Comment by veereshreddy123** [comment]
Please assign this issue to me , i am interested to work on about this issue.

**Comment by bradrydzewski** [comment]
oops!  this one has already been completed. sorry for the confusion. I will assign you the node one
https://tutorials.drone.io/publish-golang-docker-images-for-aarch64/
