### ISSUE TITLE
Publish multi-Architecture debian packages for Rust

### ISSUE THREAD

**Issue by bradrydzewski** [drone/tutorials#10]
this tutorial should focus on building arm, arm64, and amd64 deb packages for Rust and then automate publishing the deb packages with Drone.

**Comment by KN4CK3R** [comment]
Could you assign me this issue please?

**Comment by bradrydzewski** [comment]
assigned, thanks!

any thoughts on where we publish the .deb files?  we could publish the .deb files as github releases for example, but I'm open to suggestions.

**Comment by KN4CK3R** [comment]
I have planned to use https://launchpad.net/ There you can create a personal package archive usable with apt.
