### ISSUE TITLE
Create multi-Architecture GitHub releases for Go projects

### ISSUE THREAD

**Issue by bradrydzewski** [drone/tutorials#7]
this tutorial should focus on defining and building arm, arm64, and amd64 Go executables, packaging and uploading to github releases (manually). It should then describe how to automate this process using Drone and the Drone GitHub release plugin.

**Comment by ljvmiranda921** [comment]
Hi @bradrydzewski I am interested to work on this!

**Comment by bradrydzewski** [comment]
@ljvmiranda921 thanks, I have assigned you the issue.  When you are ready please post a draft via Google Docs for review. You can use [this sample](https://tutorials.drone.io/publish-golang-docker-images-for-aarch64/) tutorial for reference. Let us know if you have any questions.

**Comment by ljvmiranda921** [comment]
Ok! Let me work on it this week! Let me update you on Friday! Thanks a lot!
